diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
safe.directory=C:/yenkhana
safe.directory=C:/yenkhana
safe.directory=C:/project/PhantomX_AI
safe.directory=C:/project/PhantomX_AI
safe.directory=C:/Users/1Man.Army/phantomnet
user.name=AI1manArmy
user.email=icu@yenkhana.com
user.signingkey=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPma0a9VvuKR6Ai0O8RGLOl1Cg1IwFM+RkIBfbGhveT8
gpg.format=ssh
gpg.ssh.program=C:\Users\1Man.Army\AppData\Local\1Password\app\8\op-ssh-sign.exe
commit.gpgsign=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/MY-Checkmate/AI-Child.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
